# This file is provided as a quick way to deploy ContainerSSH for
# testing purposes. It should not be used for production.
#
# Please see the ContainerSSH reference manual for a detailed guide:
# https://containerssh.io/reference/
---
services:
  # Set environment variables used by the auth config in containerssh
  # Be sure to fill this out according to documentation
  config-seeder:
    image: alpine:latest
    volumes:
      - ./config:/config
    env_file: "./oidc.env"
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "apk add gettext && 
      envsubst < /config/config.template.yaml > /config/config.yaml"
  containerssh:
    depends_on:
      - config-seeder
    build:
      dockerfile: Dockerfile # Docker implementation, also works with podman
      # dockerfile: Containerfile # The correct way
      context: ../student-container
    image: quay.io/containerssh/containerssh:v0.5.2
    ports:
      - 2222:2222

    volumes:
      # Mount the ContainerSSH config.
    - type: bind
      source: ./config/config.yaml
      target: /etc/containerssh/config.yaml

      # Mount the SSH host key into the container.
      # This should be generated by running openssl genrsa
    - type: bind
      source: ./ssh_host_rsa_key
      target: /var/secrets/ssh_host_rsa_key
    - type: bind
      source: ./ssh_host_ed25519_key
      target: /var/secrets/ssh_host_ed25519_key

      # We are mounting the Docker socket so ContainerSSH can start containers.
      # This is not recommended for production, instead you should set up
      # TLS authentication over TCP instead. See https://containerssh.io/reference/dockerrun/
      # for details.
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

    # We are changing the user back to root so we can access the Docker socket.
    # We don't recommend using this setting in production. Please take a look
    # at https://containerssh.io/reference/dockerrun/ for hardened settings.
    user: "root"
  authconfig:
    # The test-authconfig server lets in the "foo" user with the "bar" password.
    image: containerssh/containerssh-test-authconfig:0.4.1

volumes:
  containerssh-config:
