# This file is provided as a quick way to deploy ContainerSSH for
# testing purposes. It should not be used for production.
#
# Please see the ContainerSSH reference manual for a detailed guide:
# https://containerssh.io/reference/
---
services:
  # Set environment variables used by the auth config in containerssh
  # Be sure to fill this out according to documentation
  # config-seeder:
  #   image: alpine:latest
  #   volumes:
  #     - ./config:/config:Z
  #   env_file: "./oidc.env"
  #   entrypoint: ["/bin/sh", "-c"]
  #   command: >
  #     "apk add gettext && 
  #     envsubst < /config/config.template.yaml > /config/config.yaml"
  containerssh:
    # depends_on:
    #   config-seeder:
    #     condition: service_completed_successfully
    image: quay.io/containerssh/containerssh:v0.5.2
    ports:
      - 2222:2222

    volumes:
      # Mount the ContainerSSH config.
      - ./config/config.yaml:/etc/containerssh/config.yaml:Z

      # Mount the SSH host key into the container.
      # This should be generated using ./generate_keys.sh or openssl
      - ./ssh_host_rsa_key:/var/secrets/ssh_host_rsa_key:Z
      - ./ssh_host_ed25519_key:/var/secrets/ssh_host_ed25519_key:Z

      # We are mounting the Docker socket so ContainerSSH can start containers.
      # - type: bind
      #   source: /var/run/docker.sock
      #   target: /var/run/docker.sock
      #   bind:
      #     selinux: "z"
        # Using podman socket, uid 1000 for testing
      - /var/run/user/1022/podman/podman.sock:/var/run/podman.sock:Z

    # We are using the uid/gid of the user running the podman socket on the host
    user: "1022:1022"
  # Auth server used for testing
  auth:
    image: python
    volumes:
      - ./auth/:/auth:Z
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "pip install -r /auth/requirements.txt &&
      python3 /auth/auth.py"
